### ISSUE TITLE
Not being detected by VSCode Format Document

### ISSUE THREAD

**Issue by edupgarcia** [adamrybak/graycat-sql-formatter#5] opened 2021-01-31 18:43 UTC
When I choose Format Document in VSCode, it doesn't recognize graycat as formatter for a mysql script file (filename.sql).
Is there something else I must setup to make it work?

**Comment by LegendaryMediaTV** [comment] 2021-03-03 15:49
I was able to get it working by setting the default SQL formatter for VS Code.

1. open the Command Pallete (Ctrl+Shift+P)
2. search/select "Preferences: "Open Settings JSON"
3. add and save the following (case-sensitive):

```
"[sql]": {
  "editor.defaultFormatter": "AdamRybak.graycat-sql-formatter"
},
```

Then Alt+Shift+F formats, but you can also add the following to the main level of the settings JSON file:

```
"editor.formatOnPaste": true,
"editor.formatOnSave": true,
```

Hope that helps!

**Comment by adamrybak** [comment] 2021-03-04 23:35
Thanks for the report, I will close this as it's a duplicate of #1 .

**Closed by adamrybak** 2021-03-04 23:35 UTC
